import { UserAuthProvider } from '@/contexts/UserAuthContext';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'X Clone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <UserAuthProvider>{children}</UserAuthProvider>;
}
